"""End-to-end test for FloodLLM pipeline."""
import asyncio
import sys
from pathlib import Path

# Add parent to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from app.utils.geocode import geocode_location
from app.utils.llm import LLMPromptHandler


async def test_geocoding():
    """Test location geocoding."""
    print("\n=== Testing Geocoding ===")

    # Test Jakarta
    bbox = await geocode_location("Jakarta, Indonesia")
    if bbox:
        print(f"✓ Jakarta geocoded: {bbox}")
    else:
        print("✗ Jakarta geocoding failed")

    # Test Bangkok
    bbox = await geocode_location("Bangkok, Thailand")
    if bbox:
        print(f"✓ Bangkok geocoded: {bbox}")
    else:
        print("✗ Bangkok geocoding failed")

    return True


def test_llm_parsing():
    """Test LLM prompt parsing."""
    print("\n=== Testing LLM Prompt Parsing ===")

    handler = LLMPromptHandler()

    test_prompts = [
        "Show flood extent in Jakarta for the last 7 days",
        "Assess flood risk in Bangkok this week",
        "Generate damage report for recent floods in Manila",
        "Where is flooding happening in Vietnam right now?"
    ]

    for prompt in test_prompts:
        result = handler.parse_prompt(prompt)
        print(f"\nPrompt: '{prompt}'")
        print(f"  Location: {result.get('location')}")
        print(f"  Date Range: {result.get('date_start')} to {result.get('date_end')}")
        print(f"  Task Type: {result.get('task_type')}")

    return True


def test_report_generation():
    """Test report generation without PDF dependencies."""
    print("\n=== Testing Report Generation ===")

    from app.visualization.reporter import ReportGenerator

    generator = ReportGenerator()

    test_data = {
        "location": "Jakarta, Indonesia",
        "date_range": "2024-01-01 to 2024-01-08",
        "flood_area_km2": 45.5,
        "affected_buildings": 2500,
        "affected_roads_km": 120.5,
        "agricultural_km2": 15.2,
        "rainfall_mm": 185.0,
        "risk_assessment": {
            "level": "moderate",
            "high_risk_pct": 15.0,
            "moderate_risk_pct": 35.0,
            "low_risk_pct": 50.0
        },
        "recommendations": [
            "Evacuate low-lying areas immediately",
            "Deploy emergency supplies to affected zones",
            "Monitor water levels continuously",
            "Coordinate with local emergency services"
        ],
        "narrative": None  # Will be generated by LLM
    }

    # Generate HTML report (fallback)
    report_path = generator.generate_report(test_data, "test123")
    print(f"Report generated: {report_path}")

    if Path(report_path).exists():
        print("✓ Report file created successfully")
        return True
    else:
        print("✗ Report file not found")
        return False


def test_data_structures():
    """Test core data structures."""
    print("\n=== Testing Data Structures ===")

    from app.utils.config import settings

    print(f"Base directory: {settings.base_dir}")
    print(f"Data directory: {settings.data_dir}")
    print(f"Output directory: {settings.output_dir}")

    # Verify directories exist
    assert settings.data_dir.exists(), "Data directory should exist"
    assert settings.output_dir.exists(), "Output directory should exist"

    print("✓ All directories configured correctly")
    return True


async def run_all_tests():
    """Run all end-to-end tests."""
    print("=" * 50)
    print("FloodLLM End-to-End Test Suite")
    print("=" * 50)

    results = []

    # Run tests
    results.append(("Data Structures", test_data_structures()))
    results.append(("LLM Parsing", test_llm_parsing()))
    results.append(("Geocoding", await test_geocoding()))
    results.append(("Report Generation", test_report_generation()))

    # Summary
    print("\n" + "=" * 50)
    print("TEST SUMMARY")
    print("=" * 50)

    passed = sum(1 for _, r in results if r)
    total = len(results)

    for name, result in results:
        status = "✓ PASS" if result else "✗ FAIL"
        print(f"  {status}: {name}")

    print(f"\nTotal: {passed}/{total} tests passed")

    return passed == total


if __name__ == "__main__":
    success = asyncio.run(run_all_tests())
    sys.exit(0 if success else 1)
